use-fawe-if-available: true #Should chunkbusting be done using FAWE (FastAsyncWorldEdit) if available? Highly recommended for performance reasons

max-rollbacks-per-player: 10 #Max number of chunkbust rollbacks per player (adjust this based on your player count)

disabledworlds:
  - hub
  - creative
invertworldcheck: false #If true, the list above acts like a whitelist instead

global-cooldown: false #Should chunkbuster cooldowns be shared between all chunkbusters or be per-chunkbuster type?